In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from keras.layers import Dense, Activation
from sklearn.model_selection import train_test_split

%matplotlib notebook

In [16]:
iris = pd.read_csv('Iris.csv')

In [27]:
X = iris.drop(['Id', 'Species'], axis=1)

In [51]:
target_names = y.unique()

In [55]:
dic = {n:i for i, n in enumerate(target_names)}

In [59]:
y = iris['Species'].map(dic)

In [61]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [63]:
# one hot encoding for multi-classification
y = pd.get_dummies(y)

In [66]:
y.head()

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [83]:
X_train.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
45             4.8           3.0            1.4           0.3
114            5.8           2.8            5.1           2.4
124            6.7           3.3            5.7           2.1
9              4.9           3.1            1.5           0.1
125            7.2           3.2            6.0           1.8

In [108]:
model = keras.models.Sequential()
model.add(Dense(32, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [109]:
model.fit(X_train, y_train, epochs=200)

Epoch 1/200
112/112 [==============================] - 1s 6ms/step - loss: 1.1481 - acc: 0.6339
Epoch 2/200
112/112 [==============================] - 0s 138us/step - loss: 1.0342 - acc: 0.6339
Epoch 3/200
112/112 [==============================] - 0s 121us/step - loss: 0.9448 - acc: 0.6339
Epoch 4/200
112/112 [==============================] - 0s 107us/step - loss: 0.8827 - acc: 0.6339
Epoch 5/200
112/112 [==============================] - 0s 98us/step - loss: 0.8241 - acc: 0.6964
Epoch 6/200
112/112 [==============================] - 0s 147us/step - loss: 0.7890 - acc: 0.7232
Epoch 7/200
112/112 [==============================] - 0s 147us/step - loss: 0.7662 - acc: 0.7143
Epoch 8/200
112/112 [==============================] - 0s 89us/step - loss: 0.7463 - acc: 0.7143
Epoch 9/200
112/112 [==============================] - 0s 147us/step - loss: 0.7288 - acc: 0.7143
Epoch 10/200
112/112 [==============================] - 0s 89us/step - loss: 0.7115 - acc: 0.7143
Epoch 11/200
112/112 [==

112/112 [==============================] - 0s 107us/step - loss: 0.1790 - acc: 0.9732
Epoch 166/200
112/112 [==============================] - 0s 290us/step - loss: 0.1781 - acc: 0.9732
Epoch 167/200
112/112 [==============================] - 0s 89us/step - loss: 0.1779 - acc: 0.9732
Epoch 168/200
112/112 [==============================] - 0s 94us/step - loss: 0.1764 - acc: 0.9732
Epoch 169/200
112/112 [==============================] - 0s 94us/step - loss: 0.1752 - acc: 0.9732
Epoch 170/200
112/112 [==============================] - 0s 170us/step - loss: 0.1736 - acc: 0.9732
Epoch 171/200
112/112 [==============================] - 0s 121us/step - loss: 0.1731 - acc: 0.9732
Epoch 172/200
112/112 [==============================] - 0s 98us/step - loss: 0.1727 - acc: 0.9732
Epoch 173/200
112/112 [==============================] - 0s 89us/step - loss: 0.1707 - acc: 0.9732
Epoch 174/200
112/112 [==============================] - 0s 237us/step - loss: 0.1700 - acc: 0.9732
Epoch 175/200
112/1

In [140]:
y_pred = model.predict(X_test)

In [141]:
y_pred

array([[  5.54202171e-03,   8.87443066e-01,   1.07014909e-01],
       [  1.79646467e-03,   3.77640426e-01,   6.20563149e-01],
       [  1.02382787e-02,   8.52413654e-01,   1.37347996e-01],
       [  9.94411647e-01,   5.58473822e-03,   3.68572319e-06],
       [  4.62905923e-03,   8.54101360e-01,   1.41269490e-01],
       [  9.97196078e-01,   2.80305371e-03,   8.71736972e-07],
       [  1.60605530e-03,   4.31664854e-01,   5.66729069e-01],
       [  1.88919657e-03,   4.60105419e-01,   5.38005292e-01],
       [  8.66751093e-03,   8.26405704e-01,   1.64926857e-01],
       [  2.69428128e-05,   4.36599329e-02,   9.56313193e-01],
       [  9.82569575e-01,   1.73978750e-02,   3.26048284e-05],
       [  9.95258629e-01,   4.73812316e-03,   3.16825003e-06],
       [  2.72194427e-02,   9.04617846e-01,   6.81628212e-02],
       [  7.67278112e-03,   7.59794116e-01,   2.32533127e-01],
       [  9.40573309e-03,   8.41972232e-01,   1.48621991e-01],
       [  3.04412972e-02,   8.96117806e-01,   7.3440894

In [142]:
y_test.as_matrix()[:4]

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [143]:
y_test_class = np.argmax(y_test.as_matrix(), axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [144]:
y_pred_class

array([1, 2, 1, 0, 1, 0, 2, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0,
       1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2, 2, 1, 0], dtype=int64)

In [145]:
y_test_class

array([1, 2, 1, 0, 1, 0, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0,
       1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2, 2, 1, 0], dtype=int64)

In [149]:
from sklearn.metrics import classification_report, confusion_matrix

In [150]:
print(classification_report(y_test_class, y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      0.94      0.97        18
          2       0.90      1.00      0.95         9

avg / total       0.98      0.97      0.97        38



In [152]:
confusion_matrix(y_test_class, y_pred_class)

array([[11,  0,  0],
       [ 0, 17,  1],
       [ 0,  0,  9]], dtype=int64)

In [153]:
model.evaluate?